/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        bg: 'var(--bg)',
        surface: 'var(--surface)',
        'surface-alt': 'var(--surface-alt)',
        'surface-hover': 'var(--surface-hover)',
        'surface-sunken': 'var(--surface-sunken)',
        border: 'var(--border)',
        'border-hover': 'var(--border-hover)',
        'border-strong': 'var(--border-strong)',
        text: 'var(--text)',
        'text-secondary': 'var(--text-secondary)',
        'text-tertiary': 'var(--text-tertiary)',
        'text-inverse': 'var(--text-inverse)',
        'text-heading': 'var(--text-heading)',
        accent: 'var(--accent)',
        'accent-hover': 'var(--accent-hover)',
        'accent-yellow': 'var(--accent-yellow)',
        'accent-green': 'var(--accent-green)',
        'accent-purple': 'var(--accent-purple)',
        'accent-pink': 'var(--accent-pink)',
        'accent-blue': 'var(--accent-blue)',
        // Family illustration palette (named)
        ember: 'var(--ember-orange)',
        meadow: 'var(--meadow-green)',
        sky: 'var(--sky-blue)',
        sunburst: 'var(--sunburst-yellow)',
        flamingo: 'var(--flamingo)',
        violet: 'var(--violet-pop)',
        midnight: 'var(--midnight)',
        graphite: 'var(--graphite)',
        ash: 'var(--ash)',
        success: 'var(--success)',
        error: 'var(--error)',
        warning: 'var(--warning)',
      },
      fontFamily: {
        display: ['Fraunces', 'Inter', 'Noto Sans SC', 'serif'],
        sans: ['Inter', 'Noto Sans SC', '-apple-system', 'BlinkMacSystemFont', 'sans-serif'],
        // legacy aliases used in existing JSX (kept so we don't have to refactor every call site)
        feather: ['Fraunces', 'Inter', 'Noto Sans SC', 'serif'],
        sora: ['Fraunces', 'Inter', 'Noto Sans SC', 'serif'],
        mono: ['JetBrains Mono', 'ui-monospace', 'monospace'],
      },
      boxShadow: {
        subtle: 'var(--shadow-subtle)',
        sm: 'var(--shadow-sm)',
        md: 'var(--shadow-md)',
        lg: 'var(--shadow-lg)',
      },
      borderRadius: {
        pill: 'var(--radius-pill)',
        button: 'var(--radius-button)',
        input: 'var(--radius-input)',
        card: 'var(--radius-card)',
        'card-lg': 'var(--radius-card-lg)',
        illustration: 'var(--radius-illustration)',
      },
      transitionTimingFunction: {
        'out-cubic': 'cubic-bezier(0.33, 1, 0.68, 1)',
        'out-back': 'cubic-bezier(0.34, 1.56, 0.64, 1)',
        spring: 'cubic-bezier(0.19, 1, 0.22, 1)',
      },
    },
  },
  plugins: [],
};
